#!/usr/bin/env bash
# Install the private RTMP ingest and loopback HLS origin used by /watch.
set -euo pipefail

ENV_FILE="${MV_ENV_FILE:-/etc/multiverse/deploy.env}"
DRY=0

say() { printf '     %s\n' "$*"; }
die() { printf 'STOP: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY=1 ;;
    --env-file) ENV_FILE="${2:?--env-file needs a path}"; shift ;;
    -h|--help) sed -n '2,45p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
  shift
done

[ "$(id -u)" = 0 ] || die "run this with sudo"
[ -r "$ENV_FILE" ] || die "cannot read $ENV_FILE"

# shellcheck source=/dev/null
set -a; . "$ENV_FILE"; set +a

: "${MV_USER:=multiverse}"
: "${MV_GROUP:=multiverse}"
: "${MV_PREFIX:=/opt/multiverse}"
: "${MV_STREAM_ORIGIN_ENABLED:=0}"
: "${MV_STREAM_RTMP_ADDRESS:=}"
: "${MV_STREAM_PUBLISH_CIDR:=}"
: "${MV_STREAM_HLS_BACKEND:=127.0.0.1:8888}"

[ "$MV_STREAM_ORIGIN_ENABLED" = 1 ] || { say "stream origin disabled"; exit 0; }
[ -n "$MV_STREAM_RTMP_ADDRESS" ] || die "MV_STREAM_RTMP_ADDRESS is required"
[ -n "$MV_STREAM_PUBLISH_CIDR" ] || die "MV_STREAM_PUBLISH_CIDR is required"
[ "$MV_STREAM_HLS_BACKEND" = 127.0.0.1:8888 ] || \
  die "MV_STREAM_HLS_BACKEND must stay at 127.0.0.1:8888"

case "$MV_STREAM_RTMP_ADDRESS" in
  10.*:1935|172.1[6-9].*:1935|172.2[0-9].*:1935|172.3[01].*:1935|192.168.*:1935) ;;
  *) die "MV_STREAM_RTMP_ADDRESS must be an RFC1918 IPv4 address on port 1935" ;;
esac
case "$MV_STREAM_PUBLISH_CIDR" in
  10.*/*|172.1[6-9].*/*|172.2[0-9].*/*|172.3[01].*/*|192.168.*/*) ;;
  *) die "MV_STREAM_PUBLISH_CIDR must be an RFC1918 IPv4 CIDR" ;;
esac

VERSION=1.20.0
case "$(uname -m)" in
  x86_64)
    archive="mediamtx_v${VERSION}_linux_amd64.tar.gz"
    checksum=952d5f7d31d1b448ab4da4509550594c511d42636db9d7bb175d377f4ede81df
    ;;
  aarch64|arm64)
    archive="mediamtx_v${VERSION}_linux_arm64.tar.gz"
    checksum=6aa3c03da7b6477f1e110c8e18e819cf9ef121e8981b52b8f8219982dae35f2f
    ;;
  *) die "unsupported architecture: $(uname -m)" ;;
esac

if [ "$DRY" = 1 ]; then
  say "[dry-run] install MediaMTX v$VERSION with verified SHA-256"
  say "[dry-run] bind RTMP to $MV_STREAM_RTMP_ADDRESS for $MV_STREAM_PUBLISH_CIDR"
  say "[dry-run] bind HLS to $MV_STREAM_HLS_BACKEND"
  say "[dry-run] generate a publish secret only if none exists"
  say "[dry-run] enable and start multiverse-stream.service"
  exit 0
fi

command -v curl >/dev/null || die "curl is required"
command -v openssl >/dev/null || die "openssl is required"
getent passwd "$MV_USER" >/dev/null || die "service user $MV_USER does not exist"

bin="$MV_PREFIX/bin/mediamtx"
if [ ! -x "$bin" ] || [ "$($bin --version 2>/dev/null || true)" != "v$VERSION" ]; then
  tmp="$(mktemp -d /tmp/multiverse-mediamtx.XXXXXX)"
  trap 'rm -f "$tmp/mediamtx.tgz" "$tmp/mediamtx" "$tmp/mediamtx.yml" "$tmp/LICENSE"; rmdir "$tmp" 2>/dev/null || true' EXIT
  curl -fsSL "https://github.com/bluenviron/mediamtx/releases/download/v${VERSION}/${archive}" \
    -o "$tmp/mediamtx.tgz"
  printf '%s  %s\n' "$checksum" "$tmp/mediamtx.tgz" | sha256sum -c - >/dev/null
  tar -xzf "$tmp/mediamtx.tgz" -C "$tmp" mediamtx
  install -d -m 0755 -o root -g root "$MV_PREFIX/bin"
  install -m 0755 -o root -g root "$tmp/mediamtx" "$bin"
  say "installed MediaMTX v$VERSION"
else
  say "already: MediaMTX v$VERSION"
fi

install -d -m 0750 -o root -g "$MV_GROUP" /etc/multiverse
secret_file=/etc/multiverse/stream-publish.env
if [ -s "$secret_file" ]; then
  # shellcheck source=/dev/null
  . "$secret_file"
else
  MV_STREAM_PUBLISH_USER=broadcaster
  MV_STREAM_PUBLISH_PASSWORD="$(openssl rand -hex 32)"
  umask 077
  {
    printf 'MV_STREAM_PUBLISH_USER=%s\n' "$MV_STREAM_PUBLISH_USER"
    printf 'MV_STREAM_PUBLISH_PASSWORD=%s\n' "$MV_STREAM_PUBLISH_PASSWORD"
    printf 'MV_STREAM_PUBLISH_ADDRESS=%s\n' "$MV_STREAM_RTMP_ADDRESS"
    printf 'MV_STREAM_PUBLISH_PATH=bibites\n'
  } >"$secret_file"
  chown root:"$MV_GROUP" "$secret_file"
  chmod 0640 "$secret_file"
  say "generated /etc/multiverse/stream-publish.env"
fi

case "${MV_STREAM_PUBLISH_USER:-}" in
  broadcaster) ;;
  *) die "$secret_file has an invalid publish user" ;;
esac
case "${MV_STREAM_PUBLISH_PASSWORD:-}" in
  *[!0-9a-f]*|'') die "$secret_file has an invalid publish password" ;;
esac

config_tmp="$(mktemp /etc/multiverse/mediamtx.yml.XXXXXX)"
cat >"$config_tmp" <<EOF
# Generated by deploy/install-stream-origin.sh. Re-run that script; do not edit.
logLevel: info
logDestinations: [stdout]

authMethod: internal
authInternalUsers:
  - user: $MV_STREAM_PUBLISH_USER
    pass: $MV_STREAM_PUBLISH_PASSWORD
    ips: ["$MV_STREAM_PUBLISH_CIDR"]
    permissions:
      - action: publish
        path: bibites
  - user: any
    pass:
    ips: []
    permissions:
      - action: read
        path: bibites
  - user: any
    pass:
    ips: ["127.0.0.1", "::1"]
    permissions:
      - action: metrics

api: false
metrics: true
metricsAddress: 127.0.0.1:9998
pprof: false
playback: false
rtsp: false
rtmp: true
rtmpEncryption: "no"
rtmpAddress: $MV_STREAM_RTMP_ADDRESS
hls: true
hlsAddress: $MV_STREAM_HLS_BACKEND
hlsAllowOrigins: ["https://$MV_DOMAIN"]
hlsTrustedProxies: ["127.0.0.1", "::1"]
hlsAlwaysRemux: true
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 20M
webrtc: false
srt: false
moq: false

paths:
  bibites:
    source: publisher
    overridePublisher: false
EOF
chmod 0640 "$config_tmp"
chown root:"$MV_GROUP" "$config_tmp"
mv -f "$config_tmp" /etc/multiverse/mediamtx.yml

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
install -m 0644 -o root -g root "$here/systemd/multiverse-stream.service" \
  /etc/systemd/system/multiverse-stream.service
systemctl daemon-reload
systemctl enable --now multiverse-stream.service
systemctl restart multiverse-stream.service
systemctl is-active --quiet multiverse-stream.service || die "stream origin did not start"
say "stream origin active; ingest is private and HLS is loopback-only"
say "publish credentials remain in $secret_file and were not printed"
